language: cpp

sudo: required
dist: focal

matrix:
  include:
    - os: linux
      arch: arm64
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang
            - cmake
            - cmake-data
            - libgmp-dev
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=clang
        - CMAKE_CXX_COMPILER=clang++
        - ENABLE_SHARED_LIBS=OFF
        - USE_UPNP=OFF

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang
            - cmake
            - cmake-data
            - libgmp-dev
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=clang
        - CMAKE_CXX_COMPILER=clang++
        - ENABLE_SHARED_LIBS=OFF
        - USE_UPNP=ON

    - os: linux
      compiler: g++
      arch: arm64
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - g++-9
            - libgmp-dev
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=gcc-9
        - CMAKE_CXX_COMPILER=g++-9
        - ENABLE_SHARED_LIBS=OFF
        - USE_UPNP=ON

    - os: linux
      compiler: g++
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - g++-9
            - libgmp-dev
      env:
        - CMAKE_BUILD_TYPE=DEBUG
        - CMAKE_C_COMPILER=gcc-9
        - CMAKE_CXX_COMPILER=g++-9
        - ENABLE_SHARED_LIBS=OFF
        - USE_UPNP=OFF

    - os: osx
      osx_image: xcode11.6
      compiler: clang++
      env:
        - CMAKE_BUILD_TYPE=RELEASE
        - CMAKE_C_COMPILER=clang
        - CMAKE_CXX_COMPILER=clang++
        - ENABLE_SHARED_LIBS=OFF
        - USE_UPNP=ON

before_install:
  - BUILD_PACKAGES="";
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
       export CC=clang;
       export CXX=clang++;
       export IS_TRAVIS_OSX=true;
    else
       export IS_TRAVIS_LINUX=true;
       export CC=gcc;
       export CXX=g++;
       BUILD_PACKAGES="$BUILD_PACKAGES --build-boost";
    fi;
    if [ "$USE_UPNP" = "ON" ]; then
       BUILD_PACKAGES="$BUILD_PACKAGES --build-upnpc";
    fi;
    ./install_dependencies.sh $BUILD_PACKAGES;

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
          -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
          -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
          -DENABLE_SHARED_LIBS=${ENABLE_SHARED_LIBS}
          -DUSE_UPNP=${USE_UPNP}
          ..

script:
  - make

